language: php

php:
  - 5.5
  - 5.4
  - 5.3

install:
  - sudo apt-get install python-software-properties python g++ make
  - sudo add-apt-repository ppa:chris-lea/node.js
  - sudo apt-get update
  - sudo apt-get install nodejs 
  - npm install 

before_script:
 - grunt build


